from django.core.management.base import BaseCommand
from tarot_app.models import Card

CARDS = [
    ("The Fool", "major", "", "beginnings, innocence, spontaneity, free spirit"),
    ("The Magician", "major", "", "manifestation, resourcefulness, power, inspired action"),
    ("The High Priestess", "major", "", "intuition, sacred knowledge, divine feminine, subconscious"),
    ("The Empress", "major", "", "femininity, beauty, nature, nurturing, abundance"),
    ("The Emperor", "major", "", "authority, structure, father figure, stability"),
    ("The Hierophant", "major", "", "tradition, conformity, morality, ethics"),
    ("The Lovers", "major", "", "love, harmony, relationships, values, choices"),
    ("The Chariot", "major", "", "control, willpower, success, action, determination"),
    ("Strength", "major", "", "strength, courage, patience, control, compassion"),
    ("The Hermit", "major", "", "soul searching, introspection, solitude, guidance"),
    ("Wheel of Fortune", "major", "", "good luck, karma, life cycles, destiny, turning point"),
    ("Justice", "major", "", "justice, fairness, truth, cause and effect, law"),
    ("The Hanged Man", "major", "", "pause, surrender, letting go, new perspectives"),
    ("Death", "major", "", "endings, change, transformation, transition"),
    ("Temperance", "major", "", "balance, moderation, patience, purpose, meaning"),
    ("The Devil", "major", "", "shadow self, attachment, addiction, restriction, sexuality"),
    ("The Tower", "major", "", "sudden change, upheaval, chaos, revelation, awakening"),
    ("The Star", "major", "", "hope, faith, purpose, renewal, spirituality"),
    ("The Moon", "major", "", "illusion, fear, the unconscious, dreams, confusion"),
    ("The Sun", "major", "", "positivity, fun, warmth, success, vitality"),
    ("Judgement", "major", "", "judgement, rebirth, inner calling, absolution"),
    ("The World", "major", "", "completion, integration, accomplishment, travel"),
    ("Ace of Wands", "minor", "wands", "inspiration, new opportunities, growth, potential"),
    ("Two of Wands", "minor", "wands", "future planning, progress, decisions, discovery"),
    ("Three of Wands", "minor", "wands", "expansion, foresight, overseas opportunities"),
    ("Four of Wands", "minor", "wands", "celebration, harmony, marriage, home, community"),
    ("Five of Wands", "minor", "wands", "conflict, disagreements, competition, tension"),
    ("Six of Wands", "minor", "wands", "success, public recognition, progress, self-confidence"),
    ("Seven of Wands", "minor", "wands", "challenge, competition, perseverance, protection"),
    ("Eight of Wands", "minor", "wands", "speed, action, air travel, movement, swift change"),
    ("Nine of Wands", "minor", "wands", "resilience, courage, persistence, boundaries"),
    ("Ten of Wands", "minor", "wands", "burden, extra responsibility, hard work, completion"),
    ("Page of Wands", "minor", "wands", "enthusiasm, exploration, discovery, free spirit"),
    ("Knight of Wands", "minor", "wands", "energy, passion, inspired action, adventure"),
    ("Queen of Wands", "minor", "wands", "courage, confidence, independence, social butterfly"),
    ("King of Wands", "minor", "wands", "natural leader, vision, entrepreneur, honour"),
    ("Ace of Cups", "minor", "cups", "love, new relationships, compassion, creativity"),
    ("Two of Cups", "minor", "cups", "unified love, partnership, mutual attraction"),
    ("Three of Cups", "minor", "cups", "celebration, friendship, creativity, collaborations"),
    ("Four of Cups", "minor", "cups", "meditation, contemplation, apathy, reevaluation"),
    ("Five of Cups", "minor", "cups", "regret, failure, disappointment, pessimism"),
    ("Six of Cups", "minor", "cups", "revisiting the past, childhood memories, innocence, joy"),
    ("Seven of Cups", "minor", "cups", "opportunities, choices, wishful thinking, illusion"),
    ("Eight of Cups", "minor", "cups", "disappointment, abandonment, withdrawal, escapism"),
    ("Nine of Cups", "minor", "cups", "contentment, satisfaction, gratitude, wish come true"),
    ("Ten of Cups", "minor", "cups", "divine love, blissful relationships, harmony, alignment"),
    ("Page of Cups", "minor", "cups", "creative opportunities, curiosity, possibility, daydreamer"),
    ("Knight of Cups", "minor", "cups", "creativity, romance, charm, imagination, beauty"),
    ("Queen of Cups", "minor", "cups", "compassionate, caring, emotionally stable, intuitive"),
    ("King of Cups", "minor", "cups", "emotionally balanced, compassionate, diplomatic"),
    ("Ace of Swords", "minor", "swords", "breakthroughs, new ideas, mental clarity, success"),
    ("Two of Swords", "minor", "swords", "difficult decisions, weighing options, indecision, stalemate"),
    ("Three of Swords", "minor", "swords", "heartbreak, emotional pain, sorrow, grief, hurt"),
    ("Four of Swords", "minor", "swords", "rest, relaxation, meditation, contemplation, recuperation"),
    ("Five of Swords", "minor", "swords", "conflict, disagreements, competition, defeat, winning"),
    ("Six of Swords", "minor", "swords", "transition, change, rite of passage, releasing baggage"),
    ("Seven of Swords", "minor", "swords", "betrayal, deception, getting away with something, stealth"),
    ("Eight of Swords", "minor", "swords", "imprisonment, entrapment, self-victimization, powerlessness"),
    ("Nine of Swords", "minor", "swords", "anxiety, worry, fear, depression, nightmares"),
    ("Ten of Swords", "minor", "swords", "painful endings, deep wounds, betrayal, loss, crisis"),
    ("Page of Swords", "minor", "swords", "new ideas, curiosity, thirst for knowledge, communication"),
    ("Knight of Swords", "minor", "swords", "ambitious, action-oriented, driven to succeed, fast thinking"),
    ("Queen of Swords", "minor", "swords", "independent, unbiased judgement, clear boundaries, direct"),
    ("King of Swords", "minor", "swords", "mental clarity, intellectual power, authority, truth"),
    ("Ace of Pentacles", "minor", "pentacles", "new financial opportunity, prosperity, abundance, security"),
    ("Two of Pentacles", "minor", "pentacles", "multiple priorities, time management, adaptability"),
    ("Three of Pentacles", "minor", "pentacles", "teamwork, collaboration, learning, implementation"),
    ("Four of Pentacles", "minor", "pentacles", "saving money, security, conservatism, scarcity, control"),
    ("Five of Pentacles", "minor", "pentacles", "financial loss, poverty, lack mindset, isolation, worry"),
    ("Six of Pentacles", "minor", "pentacles", "giving, receiving, sharing wealth, generosity, charity"),
    ("Seven of Pentacles", "minor", "pentacles", "long-term view, sustainable results, perseverance"),
    ("Eight of Pentacles", "minor", "pentacles", "apprenticeship, mastery, skill development, repetition"),
    ("Nine of Pentacles", "minor", "pentacles", "abundance, luxury, self-sufficiency, financial independence"),
    ("Ten of Pentacles", "minor", "pentacles", "wealth, financial security, family, long-term success"),
    ("Page of Pentacles", "minor", "pentacles", "manifestation, financial opportunity, new skills, learning"),
    ("Knight of Pentacles", "minor", "pentacles", "hard work, productivity, routine, conservatism"),
    ("Queen of Pentacles", "minor", "pentacles", "practical, homely, motherly, down-to-earth, security"),
    ("King of Pentacles", "minor", "pentacles", "wealth, business, leadership, security, discipline"),
]


class Command(BaseCommand):
    help = 'Seed the database with all 78 tarot cards'

    def handle(self, *args, **kwargs):
        if Card.objects.exists():
            self.stdout.write('Cards already seeded.')
            return
        for name, arcana, suit, keywords in CARDS:
            Card.objects.create(name=name, arcana=arcana, suit=suit, keywords=keywords)
        self.stdout.write(self.style.SUCCESS(f'Seeded {len(CARDS)} cards.'))